version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: magento-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/magento2
      - ./php.ini:/usr/local/etc/php/conf.d/memory.ini
    ports:
      - "9081:9000"
    networks:
      - magento

  db:
    image: mariadb:10.4
    ports:
      - "3307:3306"
    env_file: env/db.env
    networks:
      - magento

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - magento

  elasticsearch:
    image: elasticsearch:7.16.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    networks:
      - magento

networks:
  magento:
    driver: bridge